run:
  timeout: 30m

issues:
  exclude-files:
    - ".*\\_gen\\.go$"
    - ".*\\_gen\\_test\\.go$"
    - ".*\\_test\\.go$"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - err113
    - gofmt
    - goheader
    - mnd
    - gomoddirectives
    - gosec
    - grouper
    - loggercheck
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  goheader:
    template-path: .copyright-header
