run:
  timeout: 30m

  skip-files:
    - ".*\\_gen\\.go$"
    - ".*\\_gen\\_test\\.go$"
    - ".*\\_test\\.go$"

linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - decorder
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gomnd
    - gomoddirectives
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
