---
project_name: DMRHub

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: DMRHub

dockers:
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-amd64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv7"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-armv7"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-armv7"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-armv7"
    use: buildx
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm/v7"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-armv6"
    use: buildx
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:latest"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:latest-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}"
    image_templates:
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:{{ .Tag }}-armv7"
  - name_template: "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}"
    image_templates:
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}-armv7"
  - name_template: "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "registry.hub.docker.com/jamcswain/dmrhub:latest"
    image_templates:
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-amd64"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-arm64"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-armv6"
      - "registry.hub.docker.com/jamcswain/dmrhub:latest-armv7"

builds:
  - main: .
    binary: DMRHub
    goos:
      - darwin
      - linux
      - windows
      - openbsd
      - netbsd
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin
      - goarch: arm
        goos: windows
      - goarch: riscv
        goos: windows
      - goarch: riscv64
        goos: windows
      - goarch: arm
        goos: darwin
      - goarch: riscv64
        goos: darwin
      - goarch: riscv64
        goos: openbsd
      - goarch: riscv64
        goos: netbsd
    env:
      - CGO_ENABLED=0

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD}}"
    args:
      [
        "sign-blob",
        "--key=/tmp/cosign.key",
        "--output=${signature}",
        "${artifact}",
      ]
    artifacts: all
docker_signs:
  - artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD}}"
    args: ["sign", "--key=/tmp/cosign.key", "${artifact}"]
