---
project_name: DMRHub

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: DMRHub

builds:
  - main: .
    binary: DMRHub
    goos:
      - darwin
      - linux
      - windows
      - openbsd
      - netbsd
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    goamd64:
      - v2
      - v3

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD}}"
    args:
      [
        "sign-blob",
        "--key=/tmp/cosign.key",
        "--output=${signature}",
        "${artifact}",
      ]
    artifacts: all
