---
project_name: DMRHub

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: DMRHub

dockers:
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-amd64"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-amd64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-amd64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "docker.io/jamcswain/dmrhub:latest-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.url=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv7"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-armv7"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-armv7"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
      - "docker.io/jamcswain/dmrhub:latest-armv7"
    use: buildx
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.url=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - "--platform=linux/arm/v7"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv6"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-armv6"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-armv6"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "docker.io/jamcswain/dmrhub:latest-armv6"
    use: buildx
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.url=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-arm64"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-arm64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-arm64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "docker.io/jamcswain/dmrhub:latest-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.url=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:{{ .Tag }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/usa-reddragon/dmrhub:latest"
    image_templates:
      - "ghcr.io/usa-reddragon/dmrhub:latest-amd64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-arm64"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv6"
      - "ghcr.io/usa-reddragon/dmrhub:latest-armv7"
  - name_template: "docker.io/jamcswain/dmrhub:{{ .Tag }}"
    image_templates:
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-amd64"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-arm64"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-armv6"
      - "docker.io/jamcswain/dmrhub:{{ .Tag }}-armv7"
  - name_template: "docker.io/jamcswain/dmrhub:v{{ .Major }}"
    image_templates:
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-amd64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-arm64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-armv6"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}-armv7"
  - name_template: "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-amd64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-arm64"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv6"
      - "docker.io/jamcswain/dmrhub:v{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "docker.io/jamcswain/dmrhub:latest"
    image_templates:
      - "docker.io/jamcswain/dmrhub:latest-amd64"
      - "docker.io/jamcswain/dmrhub:latest-arm64"
      - "docker.io/jamcswain/dmrhub:latest-armv6"
      - "docker.io/jamcswain/dmrhub:latest-armv7"

builds:
  - main: .
    binary: DMRHub
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: riscv64
        goos: windows
      - goarch: arm
        goos: darwin
      - goarch: riscv64
        goos: darwin
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

milestones:
  - close: true
