version: '3'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: '--requirepass password'
    ports:
      - 6379:6379
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
