// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type redisShadow struct {
	Enabled  *bool   `json:"enabled"  toml:"enabled"  yaml:"enabled"`
	Host     *string `json:"host"     toml:"host"     yaml:"host"`
	Port     *int    `json:"port"     toml:"port"     yaml:"port"`
	Password *string `json:"password" toml:"password" yaml:"password"`
}

type databaseShadow struct {
	Driver          *string   `json:"driver"           toml:"driver"           yaml:"driver"`
	Database        *string   `json:"database"         toml:"database"         yaml:"database"`
	Host            *string   `json:"host"             toml:"host"             yaml:"host"`
	Port            *int      `json:"port"             toml:"port"             yaml:"port"`
	Username        *string   `json:"username"         toml:"username"         yaml:"username"`
	Password        *string   `json:"password"         toml:"password"         yaml:"password"`
	ExtraParameters *[]string `json:"extra-parameters" toml:"extra-parameters" yaml:"extra-parameters"`
}

type robotsTXTShadow struct {
	Mode    *string `json:"mode"    toml:"mode"    yaml:"mode"`
	Content *string `json:"content" toml:"content" yaml:"content"`
}

type cORSShadow struct {
	Enabled *bool     `json:"enabled"     toml:"enabled"     yaml:"enabled"`
	Hosts   *[]string `json:"extra-hosts" toml:"extra-hosts" yaml:"extra-hosts"`
}

type hTTPShadow struct {
	Bind           *string          `json:"bind"            toml:"bind"            yaml:"bind"`
	Port           *int             `json:"port"            toml:"port"            yaml:"port"`
	RobotsTXT      *robotsTXTShadow `json:"robots-txt"      toml:"robots-txt"      yaml:"robots-txt"`
	CORS           *cORSShadow      `json:"cors"            toml:"cors"            yaml:"cors"`
	TrustedProxies *[]string        `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	CanonicalHost  *string          `json:"canonical-host"  toml:"canonical-host"  yaml:"canonical-host"`
}

type mMDVMShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}

type openBridgeShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Bind    *string `json:"bind"    toml:"bind"    yaml:"bind"`
	Port    *int    `json:"port"    toml:"port"    yaml:"port"`
}

type iPSCShadow struct {
	Enabled   *bool   `json:"enabled"    toml:"enabled"    yaml:"enabled"`
	Bind      *string `json:"bind"       toml:"bind"       yaml:"bind"`
	Port      *int    `json:"port"       toml:"port"       yaml:"port"`
	NetworkID *uint32 `json:"network-id" toml:"network-id" yaml:"network-id"`
}

type dMRShadow struct {
	MMDVM                    *mMDVMShadow      `json:"mmdvm"                       toml:"mmdvm"                       yaml:"mmdvm"`
	OpenBridge               *openBridgeShadow `json:"openbridge"                  toml:"openbridge"                  yaml:"openbridge"`
	IPSC                     *iPSCShadow       `json:"ipsc"                        toml:"ipsc"                        yaml:"ipsc"`
	DisableRadioIDValidation *bool             `json:"disable-radio-id-validation" toml:"disable-radio-id-validation" yaml:"disable-radio-id-validation"`
	RadioIDURL               *string           `json:"radio-id-url"                toml:"radio-id-url"                yaml:"radio-id-url"`
	RepeaterIDURL            *string           `json:"repeater-id-url"             toml:"repeater-id-url"             yaml:"repeater-id-url"`
}

type sMTPShadow struct {
	Enabled    *bool   `json:"enabled"     toml:"enabled"     yaml:"enabled"`
	Host       *string `json:"host"        toml:"host"        yaml:"host"`
	Port       *int    `json:"port"        toml:"port"        yaml:"port"`
	TLS        *string `json:"tls"         toml:"tls"         yaml:"tls"`
	Username   *string `json:"username"    toml:"username"    yaml:"username"`
	Password   *string `json:"password"    toml:"password"    yaml:"password"`
	From       *string `json:"from"        toml:"from"        yaml:"from"`
	AuthMethod *string `json:"auth-method" toml:"auth-method" yaml:"auth-method"`
}

type metricsShadow struct {
	Enabled        *bool     `json:"enabled"         toml:"enabled"         yaml:"enabled"`
	Bind           *string   `json:"bind"            toml:"bind"            yaml:"bind"`
	Port           *int      `json:"port"            toml:"port"            yaml:"port"`
	TrustedProxies *[]string `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	OTLPEndpoint   *string   `json:"otlp-endpoint"   toml:"otlp-endpoint"   yaml:"otlp-endpoint"`
}

type pProfShadow struct {
	Enabled        *bool     `json:"enabled"         toml:"enabled"         yaml:"enabled"`
	Bind           *string   `json:"bind"            toml:"bind"            yaml:"bind"`
	TrustedProxies *[]string `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	Port           *int      `json:"port"            toml:"port"            yaml:"port"`
}

type configShadow struct {
	LogLevel     *string         `json:"log-level"     toml:"log-level"     yaml:"log-level"`
	Redis        *redisShadow    `json:"redis"         toml:"redis"         yaml:"redis"`
	Database     *databaseShadow `json:"database"      toml:"database"      yaml:"database"`
	Secret       *string         `json:"secret"        toml:"secret"        yaml:"secret"`
	PasswordSalt *string         `json:"password-salt" toml:"password-salt" yaml:"password-salt"`
	HTTP         *hTTPShadow     `json:"http"          toml:"http"          yaml:"http"`
	DMR          *dMRShadow      `json:"dmr"           toml:"dmr"           yaml:"dmr"`
	SMTP         *sMTPShadow     `json:"smtp"          toml:"smtp"          yaml:"smtp"`
	NetworkName  *string         `json:"network-name"  toml:"network-name"  yaml:"network-name"`
	Metrics      *metricsShadow  `json:"metrics"       toml:"metrics"       yaml:"metrics"`
	PProf        *pProfShadow    `json:"pprof"         toml:"pprof"         yaml:"pprof"`
	HIBPAPIKey   *string         `json:"hibp-api-key"  toml:"hibp-api-key"  yaml:"hibp-api-key"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Redis.Enabled = false
	set("redis.enabled", configulator.LayerDefault, "default tag")
	cfg.Redis.Port = 6379
	set("redis.port", configulator.LayerDefault, "default tag")
	cfg.Database.Driver = DatabaseDriver("sqlite")
	set("database.driver", configulator.LayerDefault, "default tag")
	cfg.Database.Database = "DMRHub.db"
	set("database.database", configulator.LayerDefault, "default tag")
	{
		lst := impl.SplitList("_pragma=foreign_keys(1),_pragma=journal_mode(WAL)", sep)
		cfg.Database.ExtraParameters = lst
		set("database.extra-parameters", configulator.LayerDefault, "default tag")
	}
	cfg.HTTP.Bind = "[::]"
	set("http.bind", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 3005
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.RobotsTXT.Mode = RobotsTXTMode("disabled")
	set("http.robots-txt.mode", configulator.LayerDefault, "default tag")
	cfg.HTTP.CORS.Enabled = false
	set("http.cors.enabled", configulator.LayerDefault, "default tag")
	cfg.DMR.MMDVM.Bind = "[::]"
	set("dmr.mmdvm.bind", configulator.LayerDefault, "default tag")
	cfg.DMR.MMDVM.Port = 62031
	set("dmr.mmdvm.port", configulator.LayerDefault, "default tag")
	cfg.DMR.OpenBridge.Enabled = false
	set("dmr.openbridge.enabled", configulator.LayerDefault, "default tag")
	cfg.DMR.OpenBridge.Bind = "[::]"
	set("dmr.openbridge.bind", configulator.LayerDefault, "default tag")
	cfg.DMR.OpenBridge.Port = 62035
	set("dmr.openbridge.port", configulator.LayerDefault, "default tag")
	cfg.DMR.IPSC.Enabled = false
	set("dmr.ipsc.enabled", configulator.LayerDefault, "default tag")
	cfg.DMR.IPSC.Bind = "[::]"
	set("dmr.ipsc.bind", configulator.LayerDefault, "default tag")
	cfg.DMR.IPSC.Port = 50000
	set("dmr.ipsc.port", configulator.LayerDefault, "default tag")
	cfg.DMR.DisableRadioIDValidation = false
	set("dmr.disable-radio-id-validation", configulator.LayerDefault, "default tag")
	cfg.DMR.RadioIDURL = "https://www.radioid.net/static/users.json"
	set("dmr.radio-id-url", configulator.LayerDefault, "default tag")
	cfg.DMR.RepeaterIDURL = "https://www.radioid.net/static/rptrs.json"
	set("dmr.repeater-id-url", configulator.LayerDefault, "default tag")
	cfg.SMTP.Enabled = false
	set("smtp.enabled", configulator.LayerDefault, "default tag")
	cfg.SMTP.Port = 25
	set("smtp.port", configulator.LayerDefault, "default tag")
	cfg.SMTP.TLS = SMTPTLS("none")
	set("smtp.tls", configulator.LayerDefault, "default tag")
	cfg.SMTP.AuthMethod = SMTPAuthMethod("none")
	set("smtp.auth-method", configulator.LayerDefault, "default tag")
	cfg.NetworkName = "DMRHub"
	set("network-name", configulator.LayerDefault, "default tag")
	cfg.Metrics.Enabled = false
	set("metrics.enabled", configulator.LayerDefault, "default tag")
	cfg.Metrics.Bind = "[::]"
	set("metrics.bind", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9000
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Enabled = false
	set("pprof.enabled", configulator.LayerDefault, "default tag")
	cfg.PProf.Bind = "[::]"
	set("pprof.bind", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 6060
	set("pprof.port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Redis != nil {
		if s.Redis.Enabled != nil {
			cfg.Redis.Enabled = *s.Redis.Enabled
			set("redis.enabled", configulator.LayerFile, file)
		}
		if s.Redis.Host != nil {
			cfg.Redis.Host = *s.Redis.Host
			set("redis.host", configulator.LayerFile, file)
		}
		if s.Redis.Port != nil {
			cfg.Redis.Port = *s.Redis.Port
			set("redis.port", configulator.LayerFile, file)
		}
		if s.Redis.Password != nil {
			cfg.Redis.Password = *s.Redis.Password
			set("redis.password", configulator.LayerFile, file)
		}
	}
	if s.Database != nil {
		if s.Database.Driver != nil {
			cfg.Database.Driver = DatabaseDriver(*s.Database.Driver)
			set("database.driver", configulator.LayerFile, file)
		}
		if s.Database.Database != nil {
			cfg.Database.Database = *s.Database.Database
			set("database.database", configulator.LayerFile, file)
		}
		if s.Database.Host != nil {
			cfg.Database.Host = *s.Database.Host
			set("database.host", configulator.LayerFile, file)
		}
		if s.Database.Port != nil {
			cfg.Database.Port = *s.Database.Port
			set("database.port", configulator.LayerFile, file)
		}
		if s.Database.Username != nil {
			cfg.Database.Username = *s.Database.Username
			set("database.username", configulator.LayerFile, file)
		}
		if s.Database.Password != nil {
			cfg.Database.Password = *s.Database.Password
			set("database.password", configulator.LayerFile, file)
		}
		if s.Database.ExtraParameters != nil {
			cfg.Database.ExtraParameters = *s.Database.ExtraParameters
			set("database.extra-parameters", configulator.LayerFile, file)
		}
	}
	if s.Secret != nil {
		cfg.Secret = *s.Secret
		set("secret", configulator.LayerFile, file)
	}
	if s.PasswordSalt != nil {
		cfg.PasswordSalt = *s.PasswordSalt
		set("password-salt", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.RobotsTXT != nil {
			if s.HTTP.RobotsTXT.Mode != nil {
				cfg.HTTP.RobotsTXT.Mode = RobotsTXTMode(*s.HTTP.RobotsTXT.Mode)
				set("http.robots-txt.mode", configulator.LayerFile, file)
			}
			if s.HTTP.RobotsTXT.Content != nil {
				cfg.HTTP.RobotsTXT.Content = *s.HTTP.RobotsTXT.Content
				set("http.robots-txt.content", configulator.LayerFile, file)
			}
		}
		if s.HTTP.CORS != nil {
			if s.HTTP.CORS.Enabled != nil {
				cfg.HTTP.CORS.Enabled = *s.HTTP.CORS.Enabled
				set("http.cors.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.Hosts != nil {
				cfg.HTTP.CORS.Hosts = *s.HTTP.CORS.Hosts
				set("http.cors.extra-hosts", configulator.LayerFile, file)
			}
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted-proxies", configulator.LayerFile, file)
		}
		if s.HTTP.CanonicalHost != nil {
			cfg.HTTP.CanonicalHost = *s.HTTP.CanonicalHost
			set("http.canonical-host", configulator.LayerFile, file)
		}
	}
	if s.DMR != nil {
		if s.DMR.MMDVM != nil {
			if s.DMR.MMDVM.Bind != nil {
				cfg.DMR.MMDVM.Bind = *s.DMR.MMDVM.Bind
				set("dmr.mmdvm.bind", configulator.LayerFile, file)
			}
			if s.DMR.MMDVM.Port != nil {
				cfg.DMR.MMDVM.Port = *s.DMR.MMDVM.Port
				set("dmr.mmdvm.port", configulator.LayerFile, file)
			}
		}
		if s.DMR.OpenBridge != nil {
			if s.DMR.OpenBridge.Enabled != nil {
				cfg.DMR.OpenBridge.Enabled = *s.DMR.OpenBridge.Enabled
				set("dmr.openbridge.enabled", configulator.LayerFile, file)
			}
			if s.DMR.OpenBridge.Bind != nil {
				cfg.DMR.OpenBridge.Bind = *s.DMR.OpenBridge.Bind
				set("dmr.openbridge.bind", configulator.LayerFile, file)
			}
			if s.DMR.OpenBridge.Port != nil {
				cfg.DMR.OpenBridge.Port = *s.DMR.OpenBridge.Port
				set("dmr.openbridge.port", configulator.LayerFile, file)
			}
		}
		if s.DMR.IPSC != nil {
			if s.DMR.IPSC.Enabled != nil {
				cfg.DMR.IPSC.Enabled = *s.DMR.IPSC.Enabled
				set("dmr.ipsc.enabled", configulator.LayerFile, file)
			}
			if s.DMR.IPSC.Bind != nil {
				cfg.DMR.IPSC.Bind = *s.DMR.IPSC.Bind
				set("dmr.ipsc.bind", configulator.LayerFile, file)
			}
			if s.DMR.IPSC.Port != nil {
				cfg.DMR.IPSC.Port = *s.DMR.IPSC.Port
				set("dmr.ipsc.port", configulator.LayerFile, file)
			}
			if s.DMR.IPSC.NetworkID != nil {
				cfg.DMR.IPSC.NetworkID = *s.DMR.IPSC.NetworkID
				set("dmr.ipsc.network-id", configulator.LayerFile, file)
			}
		}
		if s.DMR.DisableRadioIDValidation != nil {
			cfg.DMR.DisableRadioIDValidation = *s.DMR.DisableRadioIDValidation
			set("dmr.disable-radio-id-validation", configulator.LayerFile, file)
		}
		if s.DMR.RadioIDURL != nil {
			cfg.DMR.RadioIDURL = *s.DMR.RadioIDURL
			set("dmr.radio-id-url", configulator.LayerFile, file)
		}
		if s.DMR.RepeaterIDURL != nil {
			cfg.DMR.RepeaterIDURL = *s.DMR.RepeaterIDURL
			set("dmr.repeater-id-url", configulator.LayerFile, file)
		}
	}
	if s.SMTP != nil {
		if s.SMTP.Enabled != nil {
			cfg.SMTP.Enabled = *s.SMTP.Enabled
			set("smtp.enabled", configulator.LayerFile, file)
		}
		if s.SMTP.Host != nil {
			cfg.SMTP.Host = *s.SMTP.Host
			set("smtp.host", configulator.LayerFile, file)
		}
		if s.SMTP.Port != nil {
			cfg.SMTP.Port = *s.SMTP.Port
			set("smtp.port", configulator.LayerFile, file)
		}
		if s.SMTP.TLS != nil {
			cfg.SMTP.TLS = SMTPTLS(*s.SMTP.TLS)
			set("smtp.tls", configulator.LayerFile, file)
		}
		if s.SMTP.Username != nil {
			cfg.SMTP.Username = *s.SMTP.Username
			set("smtp.username", configulator.LayerFile, file)
		}
		if s.SMTP.Password != nil {
			cfg.SMTP.Password = *s.SMTP.Password
			set("smtp.password", configulator.LayerFile, file)
		}
		if s.SMTP.From != nil {
			cfg.SMTP.From = *s.SMTP.From
			set("smtp.from", configulator.LayerFile, file)
		}
		if s.SMTP.AuthMethod != nil {
			cfg.SMTP.AuthMethod = SMTPAuthMethod(*s.SMTP.AuthMethod)
			set("smtp.auth-method", configulator.LayerFile, file)
		}
	}
	if s.NetworkName != nil {
		cfg.NetworkName = *s.NetworkName
		set("network-name", configulator.LayerFile, file)
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Bind != nil {
			cfg.Metrics.Bind = *s.Metrics.Bind
			set("metrics.bind", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
		if s.Metrics.TrustedProxies != nil {
			cfg.Metrics.TrustedProxies = *s.Metrics.TrustedProxies
			set("metrics.trusted-proxies", configulator.LayerFile, file)
		}
		if s.Metrics.OTLPEndpoint != nil {
			cfg.Metrics.OTLPEndpoint = *s.Metrics.OTLPEndpoint
			set("metrics.otlp-endpoint", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Bind != nil {
			cfg.PProf.Bind = *s.PProf.Bind
			set("pprof.bind", configulator.LayerFile, file)
		}
		if s.PProf.TrustedProxies != nil {
			cfg.PProf.TrustedProxies = *s.PProf.TrustedProxies
			set("pprof.trusted-proxies", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.HIBPAPIKey != nil {
		cfg.HIBPAPIKey = *s.HIBPAPIKey
		set("hibp-api-key", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "redis", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Redis.Enabled = p
		set("redis.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "redis", "host"); ok {
		cfg.Redis.Host = v
		set("redis.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "redis", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Redis.Port = int(p)
		set("redis.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "redis", "password"); ok {
		cfg.Redis.Password = v
		set("redis.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "driver"); ok {
		cfg.Database.Driver = DatabaseDriver(v)
		set("database.driver", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "database"); ok {
		cfg.Database.Database = v
		set("database.database", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "host"); ok {
		cfg.Database.Host = v
		set("database.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Database.Port = int(p)
		set("database.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "username"); ok {
		cfg.Database.Username = v
		set("database.username", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "password"); ok {
		cfg.Database.Password = v
		set("database.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "extra-parameters"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.Database.ExtraParameters = lst
		set("database.extra-parameters", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "secret"); ok {
		cfg.Secret = v
		set("secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "password-salt"); ok {
		cfg.PasswordSalt = v
		set("password-salt", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); ok {
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = int(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "robots-txt", "mode"); ok {
		cfg.HTTP.RobotsTXT.Mode = RobotsTXTMode(v)
		set("http.robots-txt.mode", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "robots-txt", "content"); ok {
		cfg.HTTP.RobotsTXT.Content = v
		set("http.robots-txt.content", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.CORS.Enabled = p
		set("http.cors.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "extra-hosts"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORS.Hosts = lst
		set("http.cors.extra-hosts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "canonical-host"); ok {
		cfg.HTTP.CanonicalHost = v
		set("http.canonical-host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "mmdvm", "bind"); ok {
		cfg.DMR.MMDVM.Bind = v
		set("dmr.mmdvm.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "mmdvm", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.mmdvm.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.MMDVM.Port = int(p)
		set("dmr.mmdvm.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "openbridge", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.openbridge.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.OpenBridge.Enabled = p
		set("dmr.openbridge.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "openbridge", "bind"); ok {
		cfg.DMR.OpenBridge.Bind = v
		set("dmr.openbridge.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "openbridge", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.openbridge.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.OpenBridge.Port = int(p)
		set("dmr.openbridge.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "ipsc", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.IPSC.Enabled = p
		set("dmr.ipsc.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "ipsc", "bind"); ok {
		cfg.DMR.IPSC.Bind = v
		set("dmr.ipsc.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "ipsc", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.IPSC.Port = int(p)
		set("dmr.ipsc.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "ipsc", "network-id"); ok {
		p, err := strconv.ParseUint(v, 10, 32)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.network-id",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.IPSC.NetworkID = uint32(p)
		set("dmr.ipsc.network-id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "disable-radio-id-validation"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.disable-radio-id-validation",
				Source: n,
				Value:  v,
			}
		}
		cfg.DMR.DisableRadioIDValidation = p
		set("dmr.disable-radio-id-validation", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "radio-id-url"); ok {
		cfg.DMR.RadioIDURL = v
		set("dmr.radio-id-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "dmr", "repeater-id-url"); ok {
		cfg.DMR.RepeaterIDURL = v
		set("dmr.repeater-id-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.SMTP.Enabled = p
		set("smtp.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "host"); ok {
		cfg.SMTP.Host = v
		set("smtp.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.SMTP.Port = int(p)
		set("smtp.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "tls"); ok {
		cfg.SMTP.TLS = SMTPTLS(v)
		set("smtp.tls", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "username"); ok {
		cfg.SMTP.Username = v
		set("smtp.username", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "password"); ok {
		cfg.SMTP.Password = v
		set("smtp.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "from"); ok {
		cfg.SMTP.From = v
		set("smtp.from", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "smtp", "auth-method"); ok {
		cfg.SMTP.AuthMethod = SMTPAuthMethod(v)
		set("smtp.auth-method", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "network-name"); ok {
		cfg.NetworkName = v
		set("network-name", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Enabled = p
		set("metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "bind"); ok {
		cfg.Metrics.Bind = v
		set("metrics.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Port = int(p)
		set("metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.Metrics.TrustedProxies = lst
		set("metrics.trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "otlp-endpoint"); ok {
		cfg.Metrics.OTLPEndpoint = v
		set("metrics.otlp-endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Enabled = p
		set("pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "bind"); ok {
		cfg.PProf.Bind = v
		set("pprof.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.PProf.TrustedProxies = lst
		set("pprof.trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Port = int(p)
		set("pprof.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "hibp-api-key"); ok {
		cfg.HIBPAPIKey = v
		set("hibp-api-key", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"redis" + o.Separator + "enabled",
		"redis" + o.Separator + "host",
		"redis" + o.Separator + "port",
		"redis" + o.Separator + "password",
		"database" + o.Separator + "driver",
		"database" + o.Separator + "database",
		"database" + o.Separator + "host",
		"database" + o.Separator + "port",
		"database" + o.Separator + "username",
		"database" + o.Separator + "password",
		"database" + o.Separator + "extra-parameters",
		"secret",
		"password-salt",
		"http" + o.Separator + "bind",
		"http" + o.Separator + "port",
		"http" + o.Separator + "robots-txt" + o.Separator + "mode",
		"http" + o.Separator + "robots-txt" + o.Separator + "content",
		"http" + o.Separator + "cors" + o.Separator + "enabled",
		"http" + o.Separator + "cors" + o.Separator + "extra-hosts",
		"http" + o.Separator + "trusted-proxies",
		"http" + o.Separator + "canonical-host",
		"dmr" + o.Separator + "mmdvm" + o.Separator + "bind",
		"dmr" + o.Separator + "mmdvm" + o.Separator + "port",
		"dmr" + o.Separator + "openbridge" + o.Separator + "enabled",
		"dmr" + o.Separator + "openbridge" + o.Separator + "bind",
		"dmr" + o.Separator + "openbridge" + o.Separator + "port",
		"dmr" + o.Separator + "ipsc" + o.Separator + "enabled",
		"dmr" + o.Separator + "ipsc" + o.Separator + "bind",
		"dmr" + o.Separator + "ipsc" + o.Separator + "port",
		"dmr" + o.Separator + "ipsc" + o.Separator + "network-id",
		"dmr" + o.Separator + "disable-radio-id-validation",
		"dmr" + o.Separator + "radio-id-url",
		"dmr" + o.Separator + "repeater-id-url",
		"smtp" + o.Separator + "enabled",
		"smtp" + o.Separator + "host",
		"smtp" + o.Separator + "port",
		"smtp" + o.Separator + "tls",
		"smtp" + o.Separator + "username",
		"smtp" + o.Separator + "password",
		"smtp" + o.Separator + "from",
		"smtp" + o.Separator + "auth-method",
		"network-name",
		"metrics" + o.Separator + "enabled",
		"metrics" + o.Separator + "bind",
		"metrics" + o.Separator + "port",
		"metrics" + o.Separator + "trusted-proxies",
		"metrics" + o.Separator + "otlp-endpoint",
		"pprof" + o.Separator + "enabled",
		"pprof" + o.Separator + "bind",
		"pprof" + o.Separator + "trusted-proxies",
		"pprof" + o.Separator + "port",
		"hibp-api-key",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Bool(names[1], false, "Enable Redis support")
	fs.String(names[2], "", "Redis host address")
	fs.Var(impl.NewInt(6379), names[3], "Redis port")
	fs.String(names[4], "", "Redis password")
	fs.String(names[5], "sqlite", "Database driver to use. One of sqlite, postgres, or mysql")
	fs.String(names[6], "DMRHub.db", "Database name or path")
	fs.String(names[7], "", "Database host address (postgres and mysql only)")
	fs.Var(impl.NewInt(0), names[8], "Database port (postgres and mysql only)")
	fs.String(names[9], "", "Database username (postgres and mysql only)")
	fs.String(names[10], "", "Database password (postgres and mysql only)")
	fs.StringSlice(names[11], nil, "Additional parameters for the database connection, e.g., sslmode=disable")
	fs.Lookup(names[11]).DefValue = "[_pragma=foreign_keys(1),_pragma=journal_mode(WAL)]"
	fs.String(names[12], "", "Secret key for the application, used for signing and encryption of the user session. Required; use a random value of at least 15 characters")
	fs.String(names[13], "", "Salt used for hashing user passwords. Required; use a random value of at least 15 characters, different from secret")
	fs.String(names[14], "[::]", "HTTP server listen address")
	fs.Var(impl.NewInt(3005), names[15], "HTTP server port")
	fs.String(names[16], "disabled", "Mode for serving robots.txt. One of allow, disabled, or custom")
	fs.String(names[17], "", "Content of the robots.txt file when mode is custom")
	fs.Bool(names[18], false, "Enable CORS support for the HTTP server")
	fs.StringSlice(names[19], nil, "List of additional allowed CORS origins")
	fs.StringSlice(names[20], nil, "List of trusted proxy IPs for the HTTP server")
	fs.String(names[21], "", "URL the HTTP server is reached at, used for generating absolute URLs, e.g. https://dmrhub.example.com. Required")
	fs.String(names[22], "[::]", "MMDVM server listen address")
	fs.Var(impl.NewInt(62031), names[23], "MMDVM server port")
	fs.Bool(names[24], false, "Enable experimental OpenBridge server support")
	fs.String(names[25], "[::]", "OpenBridge server listen address")
	fs.Var(impl.NewInt(62035), names[26], "OpenBridge server port")
	fs.Bool(names[27], false, "Enable IPSC server support")
	fs.String(names[28], "[::]", "IPSC server listen address")
	fs.Var(impl.NewInt(50000), names[29], "IPSC server port")
	fs.Uint32(names[30], 0, "DMR network ID that identifies this server to IPSC peers. Required when IPSC is enabled")
	fs.Bool(names[31], false, "Disable validation of radio IDs in DMR packets, allowing any 7- to 9-digit number to be used as a radio ID")
	fs.String(names[32], "https://www.radioid.net/static/users.json", "URL to fetch radio ID information for validation and display purposes. Expected JSON format is the same as RadioID.net.")
	fs.String(names[33], "https://www.radioid.net/static/rptrs.json", "URL to fetch repeater information for validation and display purposes. Expected JSON format is the same as RadioID.net.")
	fs.Bool(names[34], false, "Enable SMTP support for sending emails")
	fs.String(names[35], "", "SMTP server host address")
	fs.Var(impl.NewInt(25), names[36], "SMTP server port")
	fs.String(names[37], "none", "SMTP TLS mode. One of none, starttls, or implicit")
	fs.String(names[38], "", "SMTP server username")
	fs.String(names[39], "", "SMTP server password")
	fs.String(names[40], "", "Email address to use as the sender")
	fs.String(names[41], "none", "SMTP authentication method. One of none, plain, or login")
	fs.String(names[42], "DMRHub", "Name of the DMR network, shown in the web interface")
	fs.Bool(names[43], false, "Enable metrics collection and export")
	fs.String(names[44], "[::]", "Metrics server listen address")
	fs.Var(impl.NewInt(9000), names[45], "Metrics server port")
	fs.StringSlice(names[46], nil, "List of trusted proxy IPs for the metrics server")
	fs.String(names[47], "", "OTLP endpoint for exporting OpenTelemetry tracing data")
	fs.Bool(names[48], false, "Enable PProf profiling and debugging support")
	fs.String(names[49], "[::]", "PProf server listen address")
	fs.StringSlice(names[50], nil, "List of trusted proxy IPs for the PProf server")
	fs.Var(impl.NewInt(6060), names[51], "PProf server port")
	fs.String(names[52], "", "API key for the Have I Been Pwned service, used for checking if passwords have been compromised")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "redis" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.enabled",
				Source: "--" + n,
			}
		}
		cfg.Redis.Enabled = v
		set("redis.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "redis" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.host",
				Source: "--" + n,
			}
		}
		cfg.Redis.Host = v
		set("redis.host", configulator.LayerCLI, "--"+n)
	}
	if n := "redis" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.port",
				Source: "--" + n,
			}
		}
		cfg.Redis.Port = v
		set("redis.port", configulator.LayerCLI, "--"+n)
	}
	if n := "redis" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "redis.password",
				Source: "--" + n,
			}
		}
		cfg.Redis.Password = v
		set("redis.password", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "driver"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.driver",
				Source: "--" + n,
			}
		}
		cfg.Database.Driver = DatabaseDriver(v)
		set("database.driver", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "database"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.database",
				Source: "--" + n,
			}
		}
		cfg.Database.Database = v
		set("database.database", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.host",
				Source: "--" + n,
			}
		}
		cfg.Database.Host = v
		set("database.host", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.port",
				Source: "--" + n,
			}
		}
		cfg.Database.Port = v
		set("database.port", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "username"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.username",
				Source: "--" + n,
			}
		}
		cfg.Database.Username = v
		set("database.username", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.password",
				Source: "--" + n,
			}
		}
		cfg.Database.Password = v
		set("database.password", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "extra-parameters"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.extra-parameters",
				Source: "--" + n,
			}
		}
		cfg.Database.ExtraParameters = v
		set("database.extra-parameters", configulator.LayerCLI, "--"+n)
	}
	if n := "secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "secret",
				Source: "--" + n,
			}
		}
		cfg.Secret = v
		set("secret", configulator.LayerCLI, "--"+n)
	}
	if n := "password-salt"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "password-salt",
				Source: "--" + n,
			}
		}
		cfg.PasswordSalt = v
		set("password-salt", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "robots-txt" + o.Separator + "mode"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.robots-txt.mode",
				Source: "--" + n,
			}
		}
		cfg.HTTP.RobotsTXT.Mode = RobotsTXTMode(v)
		set("http.robots-txt.mode", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "robots-txt" + o.Separator + "content"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.robots-txt.content",
				Source: "--" + n,
			}
		}
		cfg.HTTP.RobotsTXT.Content = v
		set("http.robots-txt.content", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.Enabled = v
		set("http.cors.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "extra-hosts"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.extra-hosts",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.Hosts = v
		set("http.cors.extra-hosts", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "canonical-host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.canonical-host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CanonicalHost = v
		set("http.canonical-host", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "mmdvm" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.mmdvm.bind",
				Source: "--" + n,
			}
		}
		cfg.DMR.MMDVM.Bind = v
		set("dmr.mmdvm.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "mmdvm" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.mmdvm.port",
				Source: "--" + n,
			}
		}
		cfg.DMR.MMDVM.Port = v
		set("dmr.mmdvm.port", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "openbridge" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.openbridge.enabled",
				Source: "--" + n,
			}
		}
		cfg.DMR.OpenBridge.Enabled = v
		set("dmr.openbridge.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "openbridge" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.openbridge.bind",
				Source: "--" + n,
			}
		}
		cfg.DMR.OpenBridge.Bind = v
		set("dmr.openbridge.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "openbridge" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.openbridge.port",
				Source: "--" + n,
			}
		}
		cfg.DMR.OpenBridge.Port = v
		set("dmr.openbridge.port", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "ipsc" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.enabled",
				Source: "--" + n,
			}
		}
		cfg.DMR.IPSC.Enabled = v
		set("dmr.ipsc.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "ipsc" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.bind",
				Source: "--" + n,
			}
		}
		cfg.DMR.IPSC.Bind = v
		set("dmr.ipsc.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "ipsc" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.port",
				Source: "--" + n,
			}
		}
		cfg.DMR.IPSC.Port = v
		set("dmr.ipsc.port", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "ipsc" + o.Separator + "network-id"; fs.Changed(n) {
		v, err := fs.GetUint32(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.ipsc.network-id",
				Source: "--" + n,
			}
		}
		cfg.DMR.IPSC.NetworkID = v
		set("dmr.ipsc.network-id", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "disable-radio-id-validation"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.disable-radio-id-validation",
				Source: "--" + n,
			}
		}
		cfg.DMR.DisableRadioIDValidation = v
		set("dmr.disable-radio-id-validation", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "radio-id-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.radio-id-url",
				Source: "--" + n,
			}
		}
		cfg.DMR.RadioIDURL = v
		set("dmr.radio-id-url", configulator.LayerCLI, "--"+n)
	}
	if n := "dmr" + o.Separator + "repeater-id-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "dmr.repeater-id-url",
				Source: "--" + n,
			}
		}
		cfg.DMR.RepeaterIDURL = v
		set("dmr.repeater-id-url", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.enabled",
				Source: "--" + n,
			}
		}
		cfg.SMTP.Enabled = v
		set("smtp.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.host",
				Source: "--" + n,
			}
		}
		cfg.SMTP.Host = v
		set("smtp.host", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.port",
				Source: "--" + n,
			}
		}
		cfg.SMTP.Port = v
		set("smtp.port", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "tls"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.tls",
				Source: "--" + n,
			}
		}
		cfg.SMTP.TLS = SMTPTLS(v)
		set("smtp.tls", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "username"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.username",
				Source: "--" + n,
			}
		}
		cfg.SMTP.Username = v
		set("smtp.username", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.password",
				Source: "--" + n,
			}
		}
		cfg.SMTP.Password = v
		set("smtp.password", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "from"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.from",
				Source: "--" + n,
			}
		}
		cfg.SMTP.From = v
		set("smtp.from", configulator.LayerCLI, "--"+n)
	}
	if n := "smtp" + o.Separator + "auth-method"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "smtp.auth-method",
				Source: "--" + n,
			}
		}
		cfg.SMTP.AuthMethod = SMTPAuthMethod(v)
		set("smtp.auth-method", configulator.LayerCLI, "--"+n)
	}
	if n := "network-name"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "network-name",
				Source: "--" + n,
			}
		}
		cfg.NetworkName = v
		set("network-name", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.bind",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Bind = v
		set("metrics.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.Metrics.TrustedProxies = v
		set("metrics.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "otlp-endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.otlp-endpoint",
				Source: "--" + n,
			}
		}
		cfg.Metrics.OTLPEndpoint = v
		set("metrics.otlp-endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.bind",
				Source: "--" + n,
			}
		}
		cfg.PProf.Bind = v
		set("pprof.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.PProf.TrustedProxies = v
		set("pprof.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := "hibp-api-key"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "hibp-api-key",
				Source: "--" + n,
			}
		}
		cfg.HIBPAPIKey = v
		set("hibp-api-key", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "redis":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("redis", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub redisShadow
				if err := sub.decodeJSON(dec, "redis"); err != nil {
					return err
				}
				s.Redis = &sub
			}
		case "database":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("database", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub databaseShadow
				if err := sub.decodeJSON(dec, "database"); err != nil {
					return err
				}
				s.Database = &sub
			}
		case "secret":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Secret = &str
			default:
				return configJSONError("secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password-salt":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.PasswordSalt = &str
			default:
				return configJSONError("password-salt", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "dmr":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("dmr", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub dMRShadow
				if err := sub.decodeJSON(dec, "dmr"); err != nil {
					return err
				}
				s.DMR = &sub
			}
		case "smtp":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("smtp", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub sMTPShadow
				if err := sub.decodeJSON(dec, "smtp"); err != nil {
					return err
				}
				s.SMTP = &sub
			}
		case "network-name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.NetworkName = &str
			default:
				return configJSONError("network-name", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, "metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, "pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "hibp-api-key":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.HIBPAPIKey = &str
			default:
				return configJSONError("hibp-api-key", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *redisShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Password = &str
			default:
				return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *databaseShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "driver":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Driver = &str
			default:
				return configJSONError(path+".driver", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "database":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Database = &str
			default:
				return configJSONError(path+".database", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Username = &str
			default:
				return configJSONError(path+".username", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Password = &str
			default:
				return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "extra-parameters":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".extra-parameters", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".extra-parameters"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.ExtraParameters = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "robots-txt":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".robots-txt", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub robotsTXTShadow
				if err := sub.decodeJSON(dec, path+".robots-txt"); err != nil {
					return err
				}
				s.RobotsTXT = &sub
			}
		case "cors":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".cors", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub cORSShadow
				if err := sub.decodeJSON(dec, path+".cors"); err != nil {
					return err
				}
				s.CORS = &sub
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "canonical-host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.CanonicalHost = &str
			default:
				return configJSONError(path+".canonical-host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *robotsTXTShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "mode":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Mode = &str
			default:
				return configJSONError(path+".mode", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "content":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Content = &str
			default:
				return configJSONError(path+".content", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *cORSShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "extra-hosts":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".extra-hosts", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".extra-hosts"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Hosts = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *dMRShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "mmdvm":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".mmdvm", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub mMDVMShadow
				if err := sub.decodeJSON(dec, path+".mmdvm"); err != nil {
					return err
				}
				s.MMDVM = &sub
			}
		case "openbridge":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".openbridge", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub openBridgeShadow
				if err := sub.decodeJSON(dec, path+".openbridge"); err != nil {
					return err
				}
				s.OpenBridge = &sub
			}
		case "ipsc":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".ipsc", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub iPSCShadow
				if err := sub.decodeJSON(dec, path+".ipsc"); err != nil {
					return err
				}
				s.IPSC = &sub
			}
		case "disable-radio-id-validation":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.DisableRadioIDValidation = &b
			default:
				return configJSONError(path+".disable-radio-id-validation", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "radio-id-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RadioIDURL = &str
			default:
				return configJSONError(path+".radio-id-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "repeater-id-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RepeaterIDURL = &str
			default:
				return configJSONError(path+".repeater-id-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *mMDVMShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *openBridgeShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *iPSCShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "network-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".network-id", v, err)
				}
				if raw > math.MaxUint32 {
					return configJSONError(path+".network-id", v, fmt.Errorf("%d overflows uint32", raw))
				}
				num := uint32(raw)
				s.NetworkID = &num
			default:
				return configJSONError(path+".network-id", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *sMTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "tls":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.TLS = &str
			default:
				return configJSONError(path+".tls", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Username = &str
			default:
				return configJSONError(path+".username", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Password = &str
			default:
				return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "from":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.From = &str
			default:
				return configJSONError(path+".from", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "auth-method":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.AuthMethod = &str
			default:
				return configJSONError(path+".auth-method", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "otlp-endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.OTLPEndpoint = &str
			default:
				return configJSONError(path+".otlp-endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "redis.enabled = %v\n", c.Redis.Enabled)
	fmt.Fprintf(&b, "redis.host = %v\n", c.Redis.Host)
	fmt.Fprintf(&b, "redis.port = %v\n", c.Redis.Port)
	fmt.Fprintf(&b, "redis.password = %v\n", c.Redis.Password)
	fmt.Fprintf(&b, "database.driver = %v\n", c.Database.Driver)
	fmt.Fprintf(&b, "database.database = %v\n", c.Database.Database)
	fmt.Fprintf(&b, "database.host = %v\n", c.Database.Host)
	fmt.Fprintf(&b, "database.port = %v\n", c.Database.Port)
	fmt.Fprintf(&b, "database.username = %v\n", c.Database.Username)
	fmt.Fprintf(&b, "database.password = %v\n", c.Database.Password)
	fmt.Fprintf(&b, "database.extra-parameters = %v\n", c.Database.ExtraParameters)
	fmt.Fprintf(&b, "secret = %v\n", c.Secret)
	fmt.Fprintf(&b, "password-salt = %v\n", c.PasswordSalt)
	fmt.Fprintf(&b, "http.bind = %v\n", c.HTTP.Bind)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.robots-txt.mode = %v\n", c.HTTP.RobotsTXT.Mode)
	fmt.Fprintf(&b, "http.robots-txt.content = %v\n", c.HTTP.RobotsTXT.Content)
	fmt.Fprintf(&b, "http.cors.enabled = %v\n", c.HTTP.CORS.Enabled)
	fmt.Fprintf(&b, "http.cors.extra-hosts = %v\n", c.HTTP.CORS.Hosts)
	fmt.Fprintf(&b, "http.trusted-proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "http.canonical-host = %v\n", c.HTTP.CanonicalHost)
	fmt.Fprintf(&b, "dmr.mmdvm.bind = %v\n", c.DMR.MMDVM.Bind)
	fmt.Fprintf(&b, "dmr.mmdvm.port = %v\n", c.DMR.MMDVM.Port)
	fmt.Fprintf(&b, "dmr.openbridge.enabled = %v\n", c.DMR.OpenBridge.Enabled)
	fmt.Fprintf(&b, "dmr.openbridge.bind = %v\n", c.DMR.OpenBridge.Bind)
	fmt.Fprintf(&b, "dmr.openbridge.port = %v\n", c.DMR.OpenBridge.Port)
	fmt.Fprintf(&b, "dmr.ipsc.enabled = %v\n", c.DMR.IPSC.Enabled)
	fmt.Fprintf(&b, "dmr.ipsc.bind = %v\n", c.DMR.IPSC.Bind)
	fmt.Fprintf(&b, "dmr.ipsc.port = %v\n", c.DMR.IPSC.Port)
	fmt.Fprintf(&b, "dmr.ipsc.network-id = %v\n", c.DMR.IPSC.NetworkID)
	fmt.Fprintf(&b, "dmr.disable-radio-id-validation = %v\n", c.DMR.DisableRadioIDValidation)
	fmt.Fprintf(&b, "dmr.radio-id-url = %v\n", c.DMR.RadioIDURL)
	fmt.Fprintf(&b, "dmr.repeater-id-url = %v\n", c.DMR.RepeaterIDURL)
	fmt.Fprintf(&b, "smtp.enabled = %v\n", c.SMTP.Enabled)
	fmt.Fprintf(&b, "smtp.host = %v\n", c.SMTP.Host)
	fmt.Fprintf(&b, "smtp.port = %v\n", c.SMTP.Port)
	fmt.Fprintf(&b, "smtp.tls = %v\n", c.SMTP.TLS)
	fmt.Fprintf(&b, "smtp.username = %v\n", c.SMTP.Username)
	fmt.Fprintf(&b, "smtp.password = %v\n", c.SMTP.Password)
	fmt.Fprintf(&b, "smtp.from = %v\n", c.SMTP.From)
	fmt.Fprintf(&b, "smtp.auth-method = %v\n", c.SMTP.AuthMethod)
	fmt.Fprintf(&b, "network-name = %v\n", c.NetworkName)
	fmt.Fprintf(&b, "metrics.enabled = %v\n", c.Metrics.Enabled)
	fmt.Fprintf(&b, "metrics.bind = %v\n", c.Metrics.Bind)
	fmt.Fprintf(&b, "metrics.port = %v\n", c.Metrics.Port)
	fmt.Fprintf(&b, "metrics.trusted-proxies = %v\n", c.Metrics.TrustedProxies)
	fmt.Fprintf(&b, "metrics.otlp-endpoint = %v\n", c.Metrics.OTLPEndpoint)
	fmt.Fprintf(&b, "pprof.enabled = %v\n", c.PProf.Enabled)
	fmt.Fprintf(&b, "pprof.bind = %v\n", c.PProf.Bind)
	fmt.Fprintf(&b, "pprof.trusted-proxies = %v\n", c.PProf.TrustedProxies)
	fmt.Fprintf(&b, "pprof.port = %v\n", c.PProf.Port)
	fmt.Fprintf(&b, "hibp-api-key = %v\n", c.HIBPAPIKey)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
