name: Stale PR Auto-rebaser

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**

  pull_request:
    types: [labeled]

jobs:
  auto-rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: AutoRebase
    steps:
      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ secrets.PAT }}
