name: Config Docs

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  config-docs:
    name: config docs
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.AUTO_COMMIT_APP_ID }}
          private-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: USA-RedDragon/reusable-actions/configulator-docs@764c7aee28d4145c8b84d8c550727a6924a96c7e # v2.0.25
        with:
          dir: internal/config
          type: Config
          file: doc/Configuration.md
          git-user-name: usa-reddragon-auto-commit-bot[bot]
          git-user-email: usa-reddragon-auto-commit-bot[bot]@users.noreply.github.com
