name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@529a6c6e160b4039d6251284544c13a806f65156 # v2.0.29
    with:
      setup-node: true
      docker-hub-username: jamcswain
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
