name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@d65722ccb9ea7d4e4b770754a67aecc037033f1b # v2.0.21
    with:
      setup-node: true
      docker-hub-username: jamcswain
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker-hub-password: ${{ secrets.DOCKER_PASSWORD }}
